### ISSUE TITLE
[Request] Add micro-nightly

### ISSUE THREAD

**Issue by yuuki76** [ScoopInstaller/Versions#217]
(Machine translation)
I would like to see Micro's Nightly-Build added.
Because currently there is a problem that only occurs with stable builds.
I tried to create my own manifest to try it out, but as a newbie, it was difficult for me to implement Autoupdate and I couldn't do it correctly, so I'm making a suggestion here.

**Comment by tech189** [comment]
Is this the program that you would like to add?
https://micro-manager.org/Micro-Manager_Nightly_Builds

Or is it this?
https://github.com/zyedidia/micro

**Comment by rashil2000** [comment]
micro-manager is neither in Main not in Extras.

I think they mean https://github.com/zyedidia/micro, because [micro](https://github.com/ScoopInstaller/Main/blob/master/bucket/micro.json) is present in Main.

@tech189 can you raise a PR (based on Main manifest)? Downloads can be found here https://github.com/zyedidia/micro/releases/nightly
